# Generated by Django 5.1.7 on 2025-04-05 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavouritearticle',
            unique_together={('user', 'article')},
        ),
    ]
