# Generated by Django 5.1.7 on 2025-04-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_downvotes_tip_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_delete_tips', 'Can delete any tip')]},
        ),
    ]
